os:
  - linux

language:
  - cpp

compiler:
  - gcc
  - clang

env:
  global:
    - YARP_VERBOSE=1

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq  # -qq No output except for errors

install:
  #-- Install cmake
  - sudo apt-get install cmake
  #-- Install ACE
  #-- Needed while https://github.com/robotology/yarp/blob/d790dbc/src/libYARP_dev/src/Drivers.cpp#L295 is around.
  #-- See https://github.com/robotology/QA/issues/148 for full conversation.
  - sudo apt-get install libace-dev
  #-- Install yarp
  - git clone https://github.com/robotology/yarp
  - cd yarp && mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..

before_script:
  - mkdir -p build && cd build

script:
  - cmake ..
  - make
  - sudo make install
  - sudo ldconfig
  - yarp plugin --list
  - yarp plugin --verbose ExampleLibrary
  - ldd /usr/local/lib/yarp/ExampleLibrary.so
  - echo $YARP_VERBOSE
  - exampleProgram
  - bin/testExampleLibrary

after_success:
  - sudo make uninstall

