os:
  - linux

language:
  - cpp

compiler:
  - gcc
  - clang

env:
  global:
    - YARP_VERBOSE=1

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq  # -qq No output except for errors

install:
  #-- Install cmake
  - sudo apt-get install cmake
  #-- Install yarp
  - git clone https://github.com/robotology/yarp
  - cd yarp && mkdir build && cd build
  - cmake .. -DSKIP_ACE=ON
  - make
  - sudo make install
  - cd ../..

before_script:
  - mkdir -p build && cd build

script:
  - cmake ..
  - make
  - sudo make install
  - sudo ldconfig
  - yarp plugin --list
  - yarp plugin --verbose ExampleLibrary
  - ldd /usr/local/lib/yarp/ExampleLibrary.so
  - echo $YARP_VERBOSE
  - exampleProgram
  #- bin/testExampleLibrary  # Just for now

after_success:
  - sudo make uninstall

